export { Header } from '@/components/Header/Header'
export { Footer } from '@/components/Footer/Footer'
export { HeaderTab } from '@/components/HeaderTab/HeaderTab'
export { Layout } from '@/components/Layout/Layout'
export { AboutCard } from '@/components/AboutCard/AboutCard'
